import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {

  kits: [
    {
      type: 'category',
      label: 'Java KIT',
      link: {
        type: 'doc',
        id: 'kits/java/Intro'
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs-kits/kits/java',
        },
      ]
    },
    {
      type: 'category',
      label: 'Spring KIT',
      link: {
        type: 'doc',
        id: 'kits/spring-ai/Intro'
      },
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'docs-kits/kits/spring-ai',
        },
      ]
    }
  ]
};

export default sidebars;
